#!/usr/bin/env node
import { spawnSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, readdirSync, rmSync, statSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { assertSupportedNode, claudeHookConfig, commandString, detectPlatform } from './install.mjs';

const ROOT = dirname(fileURLToPath(import.meta.url));
const REQUIRED = [
  'SKILL.md','skills/agent-continuity/SKILL.md','README.md','USAGE_GUIDE.md','AGENT_CONTINUITY.md','CONTINUE_PROMPT.md','CHANGELOG.md','LICENSE','install.sh','uninstall.sh','validate.sh','install.mjs','uninstall.mjs','validate.mjs','package.json','scripts/lib/platform.sh','scripts/agent-continuity.mjs','.claude-plugin/plugin.json','hooks/hooks.json','references/LIMITATIONS.md','references/SCHEMA.md'
];

function parseArgs(argv){const options={packageOnly:false,skipTests:false,skipClaude:false,json:false,allowNonLts:false};for(const arg of argv){if(arg==='--package-only')options.packageOnly=true;else if(arg==='--skip-tests')options.skipTests=true;else if(arg==='--skip-claude')options.skipClaude=true;else if(arg==='--json')options.json=true;else if(arg==='--allow-non-lts')options.allowNonLts=true;else if(['--help','-h'].includes(arg)){console.log('Usage: node validate.mjs [--package-only] [--skip-tests] [--skip-claude] [--json] [--allow-non-lts]');process.exit(0);}else throw new Error(`Unknown option: ${arg}`);}return options;}
function check(name,ok,detail,warning=false){return{name,ok:Boolean(ok),detail:String(detail),warning};}
function run(command,args=[],options={}){return spawnSync(command,args,{cwd:options.cwd??ROOT,env:options.env??process.env,encoding:'utf8',timeout:options.timeout??120000,maxBuffer:10*1024*1024});}
function parseFrontmatter(path){const text=readFileSync(path,'utf8');const lines=text.split(/\r?\n/);if(lines[0]?.trim()!=='---')throw new Error('SKILL.md must start with YAML frontmatter');const end=lines.slice(1).findIndex(line=>line.trim()==='---');if(end<0)throw new Error('SKILL.md frontmatter is not closed');const data={};for(const line of lines.slice(1,end+1)){if(!line.trim()||line.trimStart().startsWith('#'))continue;const match=line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);if(!match)continue;let value=match[2].trim();if(value==='true'||value==='false')value=value==='true';else if((value.startsWith('"')&&value.endsWith('"'))||(value.startsWith("'")&&value.endsWith("'")))value=value.slice(1,-1);data[match[1]]=value;}return{data,text};}
function walk(root,predicate,result=[]){for(const entry of readdirSync(root,{withFileTypes:true})){if(['.git','node_modules'].includes(entry.name))continue;const path=join(root,entry.name);if(entry.isDirectory())walk(path,predicate,result);else if(predicate(path))result.push(path);}return result;}
function packageChecks(){const checks=[];const missing=REQUIRED.filter(name=>!existsSync(join(ROOT,name)));checks.push(check('required-files',!missing.length,missing.length?`missing: ${missing.join(', ')}`:'all required files present'));const pluginEntries=existsSync(join(ROOT,'.claude-plugin'))?readdirSync(join(ROOT,'.claude-plugin')).sort():[];checks.push(check('claude-plugin-directory',JSON.stringify(pluginEntries)===JSON.stringify(['plugin.json']),`entries: ${JSON.stringify(pluginEntries)}; only plugin.json is allowed`));try{const{data,text}=parseFrontmatter(join(ROOT,'SKILL.md'));checks.push(check('skill-frontmatter',true,'frontmatter parsed'));checks.push(check('skill-name',data.name==='agent-continuity',`name=${JSON.stringify(data.name)}`));checks.push(check('skill-description',typeof data.description==='string'&&data.description.trim().length>=20,'description is present and descriptive'));checks.push(check('skill-invocation-policy',data['disable-model-invocation']!==true&&data['user-invocable']!==false,'skill remains user-invocable and model-invocable'));checks.push(check('skill-size',text.split(/\r?\n/).length<500,`${text.split(/\r?\n/).length} lines; recommended maximum is 500`));const refs=['README.md','USAGE_GUIDE.md','AGENT_CONTINUITY.md','references/LIMITATIONS.md','references/SCHEMA.md'];const missingRefs=refs.filter(name=>!text.includes(name));checks.push(check('skill-progressive-disclosure',!missingRefs.length,missingRefs.length?`not referenced: ${missingRefs.join(', ')}`:'supporting files are referenced'));}catch(error){checks.push(check('skill-frontmatter',false,error.message));}
  for(const path of walk(ROOT,p=>p.endsWith('.json'))){try{const value=JSON.parse(readFileSync(path,'utf8'));checks.push(check(`json:${relative(ROOT,path)}`,value!==undefined,'valid JSON'));}catch(error){checks.push(check(`json:${relative(ROOT,path)}`,false,error.message));}}
  try{const manifest=JSON.parse(readFileSync(join(ROOT,'.claude-plugin','plugin.json'),'utf8'));checks.push(check('plugin-name',manifest.name==='agent-continuity',`name=${JSON.stringify(manifest.name)}`));checks.push(check('plugin-display-name',manifest.displayName==='Agent Continuity',`displayName=${JSON.stringify(manifest.displayName)}`));checks.push(check('plugin-version',/^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/.test(String(manifest.version??'')),`version=${JSON.stringify(manifest.version)}`));checks.push(check('plugin-description',typeof manifest.description==='string'&&manifest.description.length>=20,'description present'));checks.push(check('plugin-author',manifest.author?.name==='Ivan Lehet',`author=${JSON.stringify(manifest.author)}`));checks.push(check('plugin-license',manifest.license==='MIT',`license=${JSON.stringify(manifest.license)}`));}catch{}
  try{const pkg=JSON.parse(readFileSync(join(ROOT,'package.json'),'utf8'));checks.push(check('package-author',pkg.author?.name==='Ivan Lehet',`author=${JSON.stringify(pkg.author)}`));checks.push(check('package-license',pkg.license==='MIT',`license=${JSON.stringify(pkg.license)}`));}catch(error){checks.push(check('package-metadata',false,error.message));}
  const licenseText=readFileSync(join(ROOT,'LICENSE'),'utf8');checks.push(check('mit-license',licenseText.startsWith('MIT License')&&licenseText.includes('Copyright (c) 2026 Ivan Lehet')&&licenseText.includes('Permission is hereby granted, free of charge'),'MIT license text and copyright owner are present'));
  const forbidden=walk(ROOT,p=>p.endsWith('.py')||p.endsWith('.pyc'));checks.push(check('python-free',!forbidden.length,forbidden.length?`Python files remain: ${forbidden.map(p=>relative(ROOT,p)).join(', ')}`:'no Python runtime or installer files'));
  const docs=walk(ROOT,p=>/\.(md|sh|json)$/.test(p)&&!p.endsWith('CHANGELOG.md')).map(p=>[p,readFileSync(p,'utf8')]);const stale=docs.filter(([,text])=>/Python 3|install\.py|validate\.py|agent_continuity\.py|AGENT_CONTINUITY_PYTHON/.test(text));checks.push(check('no-stale-python-references',!stale.length,stale.length?`stale references in: ${stale.map(([p])=>relative(ROOT,p)).join(', ')}`:'documentation and hooks are Node-only'));
  return checks;
}
function shellChecks(){const checks=[];const bash=run('bash',['--version'],{timeout:10000});if(bash.status!==0)return[check('bash-syntax',true,'Bash not found; shell validation skipped',true)];for(const file of['install.sh','uninstall.sh','validate.sh','scripts/lib/platform.sh']){const result=run('bash',['-n',join(ROOT,file)],{timeout:30000});checks.push(check(`bash-syntax:${file}`,result.status===0,(result.stdout||result.stderr||'valid Bash syntax').trim()));if(process.platform!=='win32')checks.push(check(`executable:${file}`,Boolean(statSync(join(ROOT,file)).mode&0o111),(statSync(join(ROOT,file)).mode&0o111)?'executable':'not executable'));}const sc=run('shellcheck',['--version'],{timeout:10000});if(sc.status===0){const result=run('shellcheck',['install.sh','uninstall.sh','validate.sh','scripts/lib/platform.sh'],{timeout:60000});checks.push(check('shellcheck',result.status===0,(result.stdout||result.stderr||'passed').trim()));}else checks.push(check('shellcheck',true,'ShellCheck not found; optional lint skipped',true));return checks;}
function nodeChecks(allowNonLts){const checks=[];try{assertSupportedNode({allowNonLts});checks.push(check('node-runtime',true,`${process.version} LTS ${process.release.lts||'non-LTS'}`));}catch(error){checks.push(check('node-runtime',false,error.message));}for(const path of walk(ROOT,p=>p.endsWith('.mjs'))){const result=run(process.execPath,['--check',path],{timeout:30000});checks.push(check(`node-syntax:${relative(ROOT,path)}`,result.status===0,(result.stdout||result.stderr||'valid syntax').trim()));}for(const family of['macos','linux','windows']){const host=detectPlatform({system:family==='macos'?'darwin':family==='linux'?'linux':'win32',release:'test',machine:'x64',home:family==='windows'?'C:\\Sandbox\\Test User':'/opt/test user',nodeExecutable:family==='windows'?'C:\\Program Files\\nodejs\\node.exe':'/opt/node/bin/node',isWindows:family==='windows',isMacos:family==='macos',isLinux:family==='linux',isWsl:false,nodeLts:'Krypton',nodeVersion:'v24.0.0'});const script=join(host.home,'.agent-continuity','bin','agent-continuity.mjs');const hooks=claudeHookConfig(host.node_executable,script);const handlers=Object.values(hooks.hooks).flatMap(groups=>groups.flatMap(group=>group.hooks??[]));const execForm=handlers.every(h=>h.command===host.node_executable&&Array.isArray(h.args));const command=commandString([host.node_executable,script,'hook','--provider','cursor'],host);checks.push(check(`platform-hooks:${family}`,execForm&&(!command.includes('Test User')||/["']/.test(command)),`generated ${handlers.length} exec-form hooks; command=${command}`));}return checks;}
function officialClaudeCheck(skip){if(skip)return check('claude-plugin-validate',true,'skipped by request',true);const probe=run(process.platform==='win32'?'where':'which',['claude'],{timeout:10000});if(probe.status!==0)return check('claude-plugin-validate',true,'Claude CLI not found; internal validation used',true);const result=run('claude',['plugin','validate',ROOT,'--strict'],{timeout:120000});return check('claude-plugin-validate',result.status===0,(result.stdout||result.stderr||`exit ${result.status}`).trim());}
function testsCheck(skip){if(skip)return check('unit-tests',true,'skipped by request',true);const testFiles=walk(join(ROOT,'tests'),p=>p.endsWith('.test.mjs'));const result=run(process.execPath,['--test',...testFiles],{timeout:180000});return check('unit-tests',result.status===0,(result.stdout||result.stderr||`exit ${result.status}`).trim());}
function smokeCheck(skip,allowNonLts){if(skip)return check('install-smoke',true,'skipped by package-only validation',true);const base=mkdtempSync(join(tmpdir(),'agent-continuity-'));try{const home=join(base,'home');const repo=join(base,'repo');spawnSync('git',['init',repo],{encoding:'utf8'});const env={...process.env,HOME:home,USERPROFILE:home};const args=['install.mjs',repo,'--link-mode','copy','--skip-validation','--no-backup'];if(allowNonLts)args.push('--allow-non-lts');const install=run(process.execPath,args,{env,timeout:180000});if(install.status!==0)return check('install-smoke',false,(install.stdout||install.stderr||'installer failed').trim());const runtime=join(home,'.agent-continuity','bin','agent-continuity.mjs');const doctor=run(process.execPath,[runtime,'doctor','--cwd',repo],{env,timeout:60000});return check('install-smoke',doctor.status===0,(doctor.stdout||doctor.stderr||`exit ${doctor.status}`).trim());}finally{rmSync(base,{recursive:true,force:true});}}

function main(){const options=parseArgs(process.argv.slice(2));const checks=[...packageChecks(),...shellChecks(),...nodeChecks(options.allowNonLts),officialClaudeCheck(options.skipClaude),testsCheck(options.skipTests),smokeCheck(options.packageOnly,options.allowNonLts)];const failed=checks.filter(c=>!c.ok&&!c.warning);if(options.json)console.log(JSON.stringify({ok:!failed.length,node:{version:process.version,lts:process.release.lts||null},checks},null,2));else{for(const c of checks)console.log(`${c.ok?(c.warning?'WARN':'PASS'):'FAIL'} ${c.name}: ${c.detail}`);console.log(`\nValidation ${failed.length?'failed':'passed'}: ${checks.length-failed.length}/${checks.length} checks acceptable.`);}return failed.length?1:0;}
try{process.exitCode=main();}catch(error){console.error(`ERROR: ${error.message}`);process.exitCode=1;}
